"""Story data products for LLM narrative generation."""

from agent_zero.story.generator import (
    StoryGenerator,
    StoryOutput,
    StoryProvenance,
    ToolCall,
)
from agent_zero.story.tool_definitions import get_tool_by_name, get_tool_definitions
from agent_zero.story.tools import (
    compare_scenarios,
    explain_agent_behaviour,
    get_agent_summary,
    get_caveats,
    get_drivers,
    get_headline_metrics,
    get_story_context,
    to_dict,
)
from agent_zero.story.types import (
    AgentSummary,
    AgentTypeSummary,
    AssumptionChange,
    AveragePrice,
    Caveats,
    CumulativeEmissions,
    Driver,
    HeadlineMetrics,
    KeyDifference,
    PeakCapacity,
    ScenarioComparison,
    StoryContext,
    TotalEmissions,
    TotalInvestment,
    YearRange,
)

__all__ = [
    "AgentSummary",
    "AgentTypeSummary",
    "AssumptionChange",
    "AveragePrice",
    "Caveats",
    "CumulativeEmissions",
    "Driver",
    "HeadlineMetrics",
    "KeyDifference",
    "PeakCapacity",
    "ScenarioComparison",
    "StoryContext",
    "StoryGenerator",
    "StoryOutput",
    "StoryProvenance",
    "ToolCall",
    "TotalEmissions",
    "TotalInvestment",
    "YearRange",
    "compare_scenarios",
    "explain_agent_behaviour",
    "get_agent_summary",
    "get_caveats",
    "get_drivers",
    "get_headline_metrics",
    "get_story_context",
    "get_tool_by_name",
    "get_tool_definitions",
    "to_dict",
]
